name: Docker image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker version
        run: docker version

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/serani:latest \
            -t ${{ secrets.DOCKER_USERNAME }}/serani:${{ github.sha }} .
        
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/serani:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/serani:${{ github.sha }}